language: perl
install:
  - cpanm -n YAML Clustericious Clustericious::Config Clustericious::Log Data::Dumper Digest::file IO::Uncompress::Gunzip Log::Log4perl Log::Log4perl::CommandLine Number::Bytes::Human Yars
before_script:
  - mkdir -p ~/etc
  - perl -MYAML -MMojo::IOLoop::Server -MFile::HomeDir -E 'YAML::DumpFile(File::HomeDir->my_home . "/etc/Yars.conf", { url => "http://localhost:" . Mojo::IOLoop::Server->generate_port })'
  - yars start
script: HARNESS_IS_VERBOSE=1 YC_LIVE_TESTS=1 prove -lv t
after_script: yars stop
perl:
  - "5.16"
