language: perl
install:
  - cpanm Clustericious Clustericious::Config Clustericious::Log Data::Dumper Digest::file IO::Uncompress::Gunzip Log::Log4perl Log::Log4perl::CommandLine Number::Bytes::Human Yars
script: HARNESS_IS_VERBOSE=1 YC_LIVE_TESTS=1 prove -v -Ilib t
perl:
  - "5.16"
