---
abstract: 'Yars Client'
author:
  - 'Marty Brandon<mbrandon@sesda2.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Yars-Client
provides:
  Yars::Client:
    file: lib/Yars/Client.pm
    version: 0.43
requires:
  Clustericious::Client: 0.31
  Clustericious::Config: 0.04
  JSON: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.43
